App\Entity\Log:
  collectionOperations:
    delete_all:
      method: 'DELETE'
      path: '/delete'
      controller: App\Controller\DeleteController
      defaults:
        _api_receive: false
      openapi_context:
        tags:
          - truncates
        summary: Deletes logs
        description: |
          Delete endpoint will truncates the database with logs
        operationId: searchLogs
    get_counts:
      method: 'GET'
      path: '/count'
      controller: App\Controller\CountController
      defaults:
        _api_receive: false
      openapi_context:
        tags:
        - analytics
        summary: searches logs and provides aggregated count of matches
        description: |
          Count all matching items in the logs.
        operationId: searchLogs
        parameters:
          - name: serviceNames[]
            in: query
            description: array of service names
            required: false
            style: form
            explode: true
            schema:
              type: array
              items:
                type: string
          - name: startDate
            in: query
            description: start date
            required: false
            style: form
            explode: true
            schema:
              type: string
              format: dateTime
          - name: endDate
            in: query
            description: end date
            required: false
            style: form
            explode: true
            schema:
              type: string
              format: dateTime
          - name: statusCode
            in: query
            description: filter on request status code
            required: false
            style: form
            explode: true
            schema:
              type: integer
        responses:
          "200":
            description: count of matching results
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    count:
                      type: number
          "400":
            description: bad input parameter
  itemOperations: []
