<?php

namespace App\Tests\Command;

use App\Service\Config\ConfigService;
use App\Service\Log\LogService;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Tester\CommandTester;

class GatherLogTest extends KernelTestCase
{
    private CommandTester $commandTester;
    private LogService $logService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $kernel = self::bootKernel();
        $testContainer = $kernel->getContainer()->get('test.service_container');
        $this->logService = $testContainer->get(LogService::class);
        $this->configService = $testContainer->get(ConfigService::class);

        $this->assertSame('test', $kernel->getEnvironment());

        $application = new Application($kernel);
        $command = $application->find('app:gather-log');
        $this->commandTester = new CommandTester($command);
        $this->commandTester->execute([]);
    }

    public function testGatherLogCommand(): void
    {

        $this->logService->deleteAll();
        $this->configService->deleteAll();
        $this->commandTester->execute([]);
        $this->commandTester->assertCommandIsSuccessful();
        echo $output = $this->commandTester->getDisplay();
        $this->assertStringContainsString('Successfully gathered', $output);
    }

    public function testGatherEmptyLogCommand(): void
    {
        $this->commandTester->execute([]);
        $this->commandTester->assertCommandIsSuccessful();
        echo $output = $this->commandTester->getDisplay();
        $this->assertStringContainsString('No new logs has been gathered.', $output);
    }

    public function testDebugOption(): void
    {
        $this->commandTester->execute([
            '--debug' => 'no-option-required',
        ]);
        $this->commandTester->assertCommandIsSuccessful();
        $output = $this->commandTester->getDisplay();
        $this->assertStringContainsString('Memory Consumed', $output);
    }

    public function testNoDebugOption(): void
    {
        $this->commandTester->execute([]);
        $this->commandTester->assertCommandIsSuccessful();
        $output = $this->commandTester->getDisplay();
        $this->assertStringNotContainsString('Memory Consumed', $output);
    }
}
