<?php

namespace App\Tests\Command;

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Console\Tester\CommandTester;

class GatherLogTest extends KernelTestCase
{
    private CommandTester $commandTester;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $kernel = self::bootKernel();

        $this->assertSame('test', $kernel->getEnvironment());

        $application = new Application($kernel);
        $command = $application->find('app:gather-log');
        $this->commandTester = new CommandTester($command);
    }

    public function testGatherLogCommand(): void
    {
        $this->assertTrue(true);
    }

//    public function testGatherEmptyLogCommand(): void
//    {
//        $this->commandTester->execute([]);
//        $this->commandTester->assertCommandIsSuccessful();
//        $output = $this->commandTester->getDisplay();
//        $this->assertStringContainsString('No new logs has been gathered.', $output);
//    }

    public function testDebugOption(): void
    {
        $this->commandTester->execute([
            '--debug' => 'no-option-required',
        ]);
        $this->commandTester->assertCommandIsSuccessful();
        $output = $this->commandTester->getDisplay();
        $this->assertStringContainsString('Memory Consumed', $output);
    }

    public function testNoDebugOption(): void
    {
        $this->commandTester->execute([]);
        $this->commandTester->assertCommandIsSuccessful();
        $output = $this->commandTester->getDisplay();
        $this->assertStringNotContainsString('Memory Consumed', $output);
    }
}
